const assert = require('assert'), fs = require('fs'), path = require('path'), Module = require('module')
const { loadPage, createWx, createApp, armWatchdog, ROOT } = require('./harness')
const done = armWatchdog(15000), tests=[]
const test=(name,run)=>tests.push({name,run})
const loginPath='miniapp-delivery/pages/login/index.js', docPath='miniapp-delivery/pages/mine/agreement/index.js'
const tap=type=>({currentTarget:{dataset:{type}}})
function login() {
 const wx=createWx(), navigation=[], calls=[]
 wx.navigateTo=o=>{navigation.push(o);wx.__calls.nav.push({url:o.url,type:'navigateTo'})}
 wx.login=o=>{calls.push('wx.login');o.success({code:'mock-code'})}
 const app=createApp({globalData:{isLogin:false,userInfo:null},setLoginState(data){calls.push('setLoginState');return data},routeByRole(){calls.push('routeByRole')}})
 const page=loadPage(loginPath,{wx,app,stubs:{'api/auth':{wxLoginStaff:async code=>{calls.push(['wxLoginStaff',code]);return {code:0,data:{staffId:8,role:'DELIVERY',stationId:1}}},devLogin:async role=>{calls.push(['devLogin',role]);return {code:0,data:{staffId:8,role:'DELIVERY',stationId:1}}}},'config/api':{isReleaseEnv:()=>true}}})
 return {wx,app,page,navigation,calls}
}
function doc(type) {const wx=createWx(),titles=[];wx.setNavigationBarTitle=o=>titles.push(o.title);const app=createApp({routeByRole(){throw Error('阅读不得路由登录')},setLoginState(){throw Error('阅读不得写登录态')}});const page=loadPage(docPath,{wx,app});page.onLoad(type===undefined?undefined:{type});return {wx,page,titles}}
function application(route) {
 const wx=createWx()
 let app;global.wx=wx;global.App=x=>app=x;global.getApp=()=>app;global.getCurrentPages=()=>[{route}]
 const original=Module._load;Module._load=function(request,parent,isMain){if(request==='./utils/request')return {get:async()=>{throw Error('此测试禁止网络')}};if(request==='./utils/navigation')return {};return original.apply(this,arguments)}
 try{const target=path.join(ROOT,'miniapp-delivery/app.js');delete require.cache[require.resolve(target)];require(target)}finally{Module._load=original}
 const calls=[];app.redirectToLogin=()=>calls.push('login');app.routeByRole=()=>calls.push('role');return {wx,app,calls}
}
test('registered protocol route has all four page files and no pull refresh',()=>{const cfg=JSON.parse(fs.readFileSync(path.join(ROOT,'miniapp-delivery/app.json'),'utf8'));assert.equal(cfg.pages.filter(x=>x==='pages/mine/agreement/index').length,1);for(const ext of ['js','wxml','wxss','json'])assert.ok(fs.existsSync(path.join(ROOT,docPath.replace('.js','.'+ext))));assert.equal(JSON.parse(fs.readFileSync(path.join(ROOT,docPath.replace('.js','.json')),'utf8')).enablePullDownRefresh,false)})
test('login retains visible consent notice and binds both real protocol links',()=>{const t=login(),w=fs.readFileSync(path.join(ROOT,loginPath.replace('.js','.wxml')),'utf8');assert.ok(w.includes('登录即代表你已阅读并同意'));for(const type of ['user','privacy'])assert.match(w,new RegExp('data-type="'+type+'"[^>]*bindtap="onOpenAgreement"'));for(const match of w.matchAll(/(?:bindtap|catchtap)="(\w+)"/g))assert.equal(typeof t.page[match[1]],'function',match[1]);assert.ok(!w.includes('<checkbox'))})
for(const type of ['user','privacy'])test(type+' click opens matching draft without login or agreement mutation',()=>{const t=login();t.page.onLoad();t.page.onOpenAgreement(tap(type));assert.deepStrictEqual(t.calls,[]);assert.equal(t.navigation[0].url,'/pages/mine/agreement/index?type='+type);assert.equal(t.wx.__calls.storageSet.length,0);assert.equal(t.page.data.loading,false);assert.equal(t.app.globalData.isLogin,false);assert.equal(t.page.data.agreed,undefined);const d=doc(type);assert.equal(d.titles.at(-1),type==='privacy'?'隐私政策':'用户协议');assert.equal(d.wx.__calls.storageSet.length,0)})
for(const type of [undefined,null,'','bad','PRIVACY','privacy&redirect=evil'])test('invalid login type safely falls back to user: '+String(type),()=>{const t=login();t.page.onOpenAgreement(tap(type));assert.equal(t.navigation[0].url,'/pages/mine/agreement/index?type=user');assert.equal(t.calls.length,0)})
test('missing tap event safely opens user draft',()=>{const t=login();t.page.onOpenAgreement();assert.equal(t.navigation[0].url,'/pages/mine/agreement/index?type=user')})
test('repeated clicks issue one navigation until return then permit another document',()=>{const t=login();t.page.onShow();t.page.onOpenAgreement(tap('user'));t.page.onOpenAgreement(tap('privacy'));assert.equal(t.navigation.length,1);t.navigation[0].success({errMsg:'navigateTo:ok'});t.navigation[0].complete({errMsg:'navigateTo:ok'});t.page.onOpenAgreement(tap('user'));assert.equal(t.navigation.length,1);t.page.onHide();t.wx.navigateBack({delta:1});t.page.onShow();t.page.onOpenAgreement(tap('privacy'));assert.equal(t.navigation.length,2);assert.equal(t.navigation[1].url,'/pages/mine/agreement/index?type=privacy');assert.equal(t.calls.length,0);assert.equal(t.wx.__calls.storageSet.length,0)})
test('pending native navigation stays single flight across hide and show',()=>{const t=login();t.page.onShow();t.page.onOpenAgreement(tap('user'));t.page.onHide();t.page.onShow();t.page.onOpenAgreement(tap('privacy'));assert.equal(t.navigation.length,1);t.navigation[0].fail({errMsg:'native failure'});t.page.onOpenAgreement(tap('privacy'));assert.equal(t.navigation.length,2)})
test('navigation failure releases lock and gives a readable retry hint',()=>{const t=login();t.page.onOpenAgreement(tap('user'));t.navigation[0].fail({errMsg:'internal native error'});assert.equal(t.wx.__calls.toast.at(-1).title,'协议暂时无法打开，请重试');t.page.onOpenAgreement(tap('privacy'));assert.equal(t.navigation.length,2);assert.equal(t.calls.length,0)})
test('thrown navigation and complete-only failure both release lock',()=>{const t=login();t.wx.navigateTo=()=>{throw Error('native failure')};t.page.onOpenAgreement(tap('user'));assert.equal(t.wx.__calls.toast.length,1);t.wx.navigateTo=o=>t.navigation.push(o);t.page.onOpenAgreement(tap('user'));t.navigation[0].complete({errMsg:'navigateTo:fail'});t.page.onOpenAgreement(tap('privacy'));assert.equal(t.navigation.length,2)})
test('hidden and unloaded callbacks cannot toast or open another page',()=>{const t=login();t.page.onOpenAgreement(tap('user'));t.page.onHide();t.navigation[0].fail({errMsg:'late'});t.page.onOpenAgreement(tap('privacy'));assert.equal(t.navigation.length,1);assert.equal(t.wx.__calls.toast.length,0);t.page.onUnload();t.page.onShow();t.page.onOpenAgreement(tap('user'));assert.equal(t.navigation.length,1)})
test('reading during login request does not navigate or modify loading',()=>{const t=login();t.page.setData({loading:true});t.page.onOpenAgreement(tap('user'));assert.equal(t.navigation.length,0);assert.equal(t.page.data.loading,true);assert.equal(t.calls.length,0)})
for(const type of ['user','privacy'])test(type+' document keeps explicit unaudited notice and every section pending',()=>{const t=doc(type),d=t.page.data.doc;assert.equal(d.updatedAt,'草稿 · 未审核');assert.ok(d.notice.includes('占位草稿'));assert.ok(d.notice.includes('尚未'));assert.ok(d.sections.length>=5);for(const section of d.sections){assert.ok(section.heading);assert.ok(section.body.startsWith('【待补】'))};assert.ok(!JSON.stringify(d).includes('客服与反馈'))})
for(const type of [undefined,null,'unknown','Privacy','privacy?type=user'])test('invalid document type renders user draft: '+String(type),()=>{const t=doc(type);assert.equal(t.titles[0],'用户协议');assert.ok(t.page.data.doc.docTitle.includes('员工'))})
test('document renders notice, sections and titles without agreement or login controls',()=>{const w=fs.readFileSync(path.join(ROOT,docPath.replace('.js','.wxml')),'utf8');for(const field of ['doc.notice','doc.updatedAt','doc.docTitle','doc.sections','item.heading','item.body'])assert.ok(w.includes(field));assert.ok(!/<(?:button|checkbox)/.test(w));assert.ok(!w.includes('客服与反馈'))})
test('app foreground guard leaves logged-out protocol readable without login or network',()=>{const t=application('pages/mine/agreement/index');t.app.onShow();assert.deepStrictEqual(t.calls,[]);assert.equal(t.app.globalData.isLogin,false)})
test('logged-out protocol stays readable through actual app guard',()=>{const t=application('pages/mine/agreement/index');assert.equal(t.app.checkLoginState(),true);assert.deepStrictEqual(t.calls,[])})
for(const route of ['pages/home/index','pages/mine/agreement/index/extra','pages/role-select/index'])test('public protocol exception does not unlock unauthenticated '+route,()=>{const t=application(route);assert.equal(t.app.checkLoginState(),false);assert.deepStrictEqual(t.calls,['login'])})
test('logged-in reading does not select role or restore login',()=>{const t=application('pages/mine/agreement/index');const key=require(path.join(ROOT,'miniapp-delivery/utils/storage-keys')).STORAGE_KEYS.ACCESS_TOKEN;t.wx.setStorageSync(key,'mock-token');assert.equal(t.app.checkLoginState(),true);assert.deepStrictEqual(t.calls,[])})
test('reading leaves original explicit login actions callable and unchanged',async()=>{const t=login();t.page.onOpenAgreement(tap('user'));assert.equal(t.calls.length,0);t.navigation[0].success({errMsg:'navigateTo:ok'});t.page.onHide();t.page.onShow();await t.page.onWxLogin();assert.deepStrictEqual(t.calls,['wx.login',['wxLoginStaff','mock-code'],'setLoginState','routeByRole']);assert.equal(t.page.data.loading,false);assert.equal(t.page.data.agreed,undefined)})
test('explicit developer login still uses its original role and success routing',async()=>{const t=login();t.page.onDevLogin();await new Promise(resolve=>setImmediate(resolve));assert.deepStrictEqual(t.calls,[['devLogin','DELIVERY'],'setLoginState','routeByRole']);assert.equal(t.page.data.loading,false)})
;(async()=>{let failed=0;for(const t of tests){try{await t.run();console.log('PASS '+t.name)}catch(e){failed++;console.error('FAIL '+t.name+' '+e.stack)}}done();console.log('RESULT '+(tests.length-failed)+'/'+tests.length);if(failed)process.exitCode=1;else console.log('AQUAFLOW_SUITE_OK '+tests.length)})()
